namespace Fingerprinter;

public enum ErrorCode : byte {
    Ok = 0x00,
    PacketReceiveError = 0x01,
    NoFinger = 0x02,
    ImageFail = 0x03,
    ImageMess = 0x06,
    FeatureFail = 0x07,
    NoMatch = 0x08,
    NotFound = 0x09,
    EnrollMismatch = 0x0A,
    BadLocation = 0x0B,
    DbRangeFail = 0x0C,
    UploadFeatureFail = 0x0D,
    PacketResponseFail = 0x0E,
    UploadFail = 0x0F,
    DeleteFail = 0x10,
    DbClearFail = 0x11,
    PassFail = 0x13,
    InvalidImage = 0x15,
    FlashErr = 0x18,
    InvalidReg = 0x1A,
    AddrCode = 0x20,
    PassVerify = 0x21,
    Timeout = 0xFF,
    BadPacket = 0xFE,
    PortClosed = 0xFD,
}
